version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myflixapp
    container_name: app1
    restart: unless-stopped
    volumes:
      - ./:/var/www

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    image: nginx
    container_name: webserver1
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app1
    links:
      - db

  db:
    image: mysql
    container_name: db1
    environment:
      MYSQL_DATABASE: myflix
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql


  phpmyadmin:
    container_name: phpmyadmin2
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8089:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
volumes:
  dbdata:
    driver: local

  
